### ISSUE TITLE
Restarting listening for Linux DBus signals on Firefox regaining focus

### ISSUE THREAD

**Issue by davidjb** [carlin-q-scott/browser-media-keys#10]
As mentioned in #7, there's a caveat for Linux DBus support that another DBus application (eg Rhythmbox) opens after Media Keys starts listening to DBus, that application takes over listening and Media Keys won't get any signals until that application exits. 

Normally, other DBus applications (the ones I've seen, like Rhythmbox) take DBus precedence back (eg they restart listening) if/when they re-gain focus.  So, what Media Keys should do is restart listening (eg ``DetachEventListeners`` and ``AttachEventListeners`` in the DBus module) upon Firefox regaining focus to one of its windows.  

This isn't a huge issue for me as quitting the other application is just as easy to do (or disable/re-enable Media Keys), but it's worth mentioning in case a fix is simple.  It might be too much overhead to worry about.

**Comment by carlin-q-scott** [comment]
Well we're already listening for a media website tab to activate in hotkeyManager.js so it shouldn't be too difficult to pass that event to the Linux media key module.

**Comment by davidjb** [comment]
Ah yes, I found this last night as I was testing.  Here's a solution: #12

There might be a better way of type-checking the hotkey manager, but this seems to be the simplest option.
