### ISSUE TITLE
"Not available for my platform"

### ISSUE THREAD

**Issue by Nuc1eoN** [carlin-q-scott/browser-media-keys#101]
Hi :) Unfortunately I am unable to install this addon, because the website says it is "not available" for my platform. How can that be?
Specs:
ff v49.0.2
Win 7 64 bit

**Comment by Noitidart** [comment]
This is because the latest version was released only for mac/linux support. Please download the previous version from the releases page - https://addons.mozilla.org/en-US/firefox/addon/media-keys/versions/

Please grab v0.7.9

**Comment by Nuc1eoN** [comment]
Thank you
