### ISSUE TITLE
Pin media keys missing in Firefox 50.0.1

### ISSUE THREAD

**Issue by X-Ryl669** [carlin-q-scott/browser-media-keys#105]
I used to have "Pin media keys" on contextual menu for a tab on previous version of Firefox, and now it's gone.

**Comment by carlin-q-scott** [comment]
Did it make it's way back to your tabs? I have Firefox 51 installed and the pin context menu works for me.

**Comment by carlin-q-scott** [comment]
Pin context menu has been replace with normal tab pinning. So pinned tabs take precedence over unpinned tabs.
