### ISSUE TITLE
Webextension

### ISSUE THREAD

**Issue by Noitidart** [carlin-q-scott/browser-media-keys#108]
Hey @carlin-q-scott I'm working on a webextension that handles the global hotkeys. I let other addons hook into it so they can get a global hotkey from it. I was wondering if you could start working on a webextension that does just the media stuff with a local hotkey? Then we can subscribe to the global from my extension. I plan to release a Windows version of my addon within a week.

**Comment by carlin-q-scott** [comment]
I do want to do that that actually. Considering it has been over a month, have you completed the Key webextension?

**Comment by Noitidart** [comment]
I made really awesome progress. I am just completing the linux part (working with @gmelikov - i havent worked on it for the past week+ though i got busy with some stuff). You can test it out on windows though here please - https://github.com/carlin-q-scott/browser-media-keys/issues/86#issuecomment-276106408

I wrote up the play/pause next and prev to work on youtube, its very crude. I use async/await and used babel online to transpile it, the details are in the comments at top most line. :)

**Comment by Noitidart** [comment]
Also the external messaging API (communication between extensions) hasn't yet landed. So the only thing we can do for now is write a user script for Trigger. But ideally, we'll move them to Media Keys once the external messaging API lands, as we don't want to strand the thousands of users currently have.

**Comment by carlin-q-scott** [comment]
Cool, I'll take a look sometime next week. I looked briefly at Firefox's current WebExtension API progress and the context menu API is currently in progress on their Trello board so pinning won't work yet. I also have my doubts that they'll support modifying the tab context menu as I had to use non-jpm methods for that.

**Comment by carlin-q-scott** [comment]
I created a new repo for this at carlin-q-scott/browser-media-players@416a7ed765 . It's already working in Chrome and Opera but Firefox (FF) doesn't support media key commands in WebExtensions yet so I'm stuck with using normal key combos when testing in FF.

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/148

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/149

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/150

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-players/issues/1

**Comment by svnpenn** [comment]
@carlin-q-scott why was this closed if WebExtension is still not implemented?

**Comment by svnpenn** [comment]
@carlin-q-scott @Noitidart see this update:

http://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands#Media_keys

**Comment by Noitidart** [comment]
@svnpenn I don't think it works in Firefox yet based on the browser compat chart - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility

**Comment by svnpenn** [comment]
@Noitidart now that I think about it, really just using `F8` or something would
work for me, so that is not a dealbreaker.

However what is a dealbreaker is that your link also shows that `global` is
currently only supported with Chrome and Opera. That means until Firefox
implements `global` WebExtension shortcuts will only work if the browser has
focus:

http://developer.chrome.com/apps/commands#scope

**Comment by Noitidart** [comment]
Thanks @svnpenn for that indepth look. Yep global is what this is all about for sure. Totally agree with you.

**Comment by svnpenn** [comment]
@Noitidart looks like `global` will not be in 57, but maybe 58:

http://bugzilla.mozilla.org/show_bug.cgi?id=1411795

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/20

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/21

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/153

**Comment by svnpenn** [comment]
Firefox 57 is less than a week away, with [media keys][1251795] and
[global keys][1411795] still not implemented. Until this happens, you can stop
Firefox from automatically installing updates:

~~~js
Services.prefs.setBoolPref('app.update.auto', false);
~~~

[1411795]://bugzilla.mozilla.org/show_bug.cgi?id=1411795
[1251795]://bugzilla.mozilla.org/show_bug.cgi?id=1251795

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/155
