### ISSUE TITLE
Update AMO description

### ISSUE THREAD

**Issue by davidjb** [carlin-q-scott/browser-media-keys#11]
After #7, can the description and "about this addon" at https://addons.mozilla.org/en-US/firefox/addon/media-keys/ be updated to reflect the changes in the add-on (eg Google Play support & Linux support via DBus)?

Thanks.

**Comment by carlin-q-scott** [comment]
I'm almost ready to release version 0.5; I just need to deal with the long inline script in the youtube-orchestrator which resulted in a warning from the Mozilla add-on review system.

**Comment by carlin-q-scott** [comment]
Finally submitted! Just waiting on review now. You can already download it though: https://addons.mozilla.org/en-US/firefox/addon/media-keys/versions/0.6.0

**Comment by davidjb** [comment]
Super, that's great. If I notice anything amiss, I'll let you know. That
said, I've been using the latest version built from source across my three
Ubuntu machines over the last week without any issues so I don't anticipate
anything (aside from Google changing their page structure!).
