### ISSUE TITLE
"Not available for your platform" Bug

### ISSUE THREAD

**Issue by DavidCao22** [carlin-q-scott/browser-media-keys#112]
Cannot install from Firefox Addons website. I'm running Windows 10 v1607, Firefox 50.1.0 x64, HP Envy 17. I was able to use it before and really enjoyed it. But, my guess is that it was, the transition from x32 to x64, the jump to Firefox 50, or something about WebExtensions that broke it. Would really like to see this be fixed.

**Comment by Aryetis** [comment]
Same here with Windows 8.0 X64 and Firefox 51.0b13 (32 bits)

**Comment by will-l-h** [comment]
+1

**Comment by carlin-q-scott** [comment]
I am also experiencing this issue now and I'm not sure what's causing it as everything checks out in the add-on manager for me:

- [x] marked as compatible with current firefox
- [x] compatability reports green for current firefox
- [x] multiprocess firefox compatible
- [x] ???

**Comment by Aryetis** [comment]
It's a windows specific problem anyways, not directly related to es support

**Comment by carlin-q-scott** [comment]
I found the problem I think. I released a newer version of the add-on for other platforms and mozilla has chosen to "try" to provide that version for Windows users who should be using the older version. You can install the MediaKeys by hovering over version 0.7.9 here: https://addons.mozilla.org/en-US/firefox/addon/media-keys/versions/?page=1#version-0.7.9.

I'll work around this soon by releasing a newer version for all platforms.

**Comment by carlin-q-scott** [comment]
Uploaded new version for all platforms, awaiting review from Noitidart .
