### ISSUE TITLE
Support listen.tidal.com

### ISSUE THREAD

**Issue by TormodLandet** [carlin-q-scott/browser-media-keys#113]
The tidalhifi.com domain seems to be discontinued? At least I get a redirect to tidal.com.

On the listen.tidal.com page the (hopefully) relevant source for the controls is pasted below (one of the Play/Pause buttons are "display: none" depending on state).

I tried to change my installed version of the extension, but I cannot get firefox to allow me to load it since the extension signature no longer matches the xpi

```html
<div class="player__play-controls play-controls" data-subview="playControls"><div data-subview="volumeControlPlayControls"></div>

<button class="play-controls__shuffle js-shuffle" data-i18n-title="t-shuffle" title="Shuffle" data-i18n-label="t-shuffle" aria-label="Shuffle" data-test-id="shuffle"><i class="icon-crossing-arrows"></i></button>
<button class="play-controls__previous js-previous" data-i18n-title="t-previous" title="Previous" data-i18n-label="t-previous" aria-label="Previous" data-test-id="previous"><i class="icon-fast-backward"></i></button>
<div class="play-controls__main-button js-main-button play-controls__main-button--playing">
  <button class="play-controls__play js-play" data-i18n-title="t-play" title="Play" data-i18n-label="t-play" aria-label="Play" data-test-id="play"><i class="icon-play"></i></button>
  <button class="play-controls__pause js-pause" data-i18n-title="t-pause" title="Pause" data-i18n-label="t-pause" aria-label="Pause" data-test-id="pause"><i class="icon-pause"></i></button>
  <i class="play-controls__loader is-loading"></i>
</div>
```

**Comment by carlin-q-scott** [comment]
Thanks for the thorough report! I'll look at this right away.

**Comment by carlin-q-scott** [comment]
Is there no button for playing the next track? All these buttons look the same except that one's absent.

**Comment by TormodLandet** [comment]
Yes, sorry, there is of course. Don't know why I didn't include it

``` HTML
<button class="play-controls__next js-next" data-i18n-title="t-next" title="Next" data-i18n-label="t-next" aria-label="Next" data-test-id="next">
  <i class="icon-Playback_next"></i>
</button>
```

**Comment by carlin-q-scott** [comment]
Thanks for providing all the needed info @TormodLandet . They didn't actually change the player, just the domain. The HTML was still helpful though as I needed to verify that they didn't change anything when they switched domains.

The fix went out on the 27th of April.
