### ISSUE TITLE
stopped working with the new Pandora website

### ISSUE THREAD

**Issue by caente** [carlin-q-scott/browser-media-keys#118]
After pandora updated its website the media keys stopped working -- on pandora, everything else works fine. 

I've tested it on mac and fedora 25

**Comment by carlin-q-scott** [comment]
Already fixed but I haven't pushed the release out yet.

**Comment by caente** [comment]
awesome! thanks

**Comment by ksariash** [comment]
fix should be something along the lines of...
MediaKeys.playButton = "//div[@class='PlayButton' and contains(@data-qa,'pause_button')]";
MediaKeys.pauseButton = "//div[@class='PlayButton' and contains(@data-qa,'play_button')]";

**Comment by carlin-q-scott** [comment]
This is fixed btw.
