### ISSUE TITLE
New Spotify site/layout

### ISSUE THREAD

**Issue by rovo89** [carlin-q-scott/browser-media-keys#119]
Spotify has changed their layout and domain. The web player is available on https://open.spotify.com/ and the media keys are obviously not working there. Any chance you can add support for the new site? Thanks!

Tested on Windows 10 with Firefox 51.0.1, media keys are working fine for e.g. YouTube.

**Comment by CennoxX** [comment]
I've started to work on this problem,[[1]](https://github.com/carlin-q-scott/browser-media-keys/compare/master...CennoxX:master) but while everything else is working, for some reason I can't get the play/pause key running...

**Comment by gcapd** [comment]
Just a note, in my case I still have the old layout and domain (play.spotify.com), while some colleagues got the new layout. 
Maybe it is not a good idea to completely remove the play.spotify domain and old interface if the new layout is not (yet) rolled for everyone.

**Comment by CennoxX** [comment]
Okay, I didn't know that the play.spotify.com is still out there...

**Comment by rovo89** [comment]
> Just a note, in my case I still have the old layout

I'd love to go back to that, I think the new layout is terrible. Everything's so big that I scaled it down to 80% and would make it even smaller if the player controls and left sidebar were still usable. Also, they no longer update the title bar with the current song information.

> I've started to work on this problem

Thanks! Not sure what I'd have to do to test it (and I don't have the time right now to figure it out), but your changes look correct to me. No idea why it would work for "next" but not for "play/pause". By the way, if possible, you might want to use `spoticon-skip-forward-*` instead of `spoticon-skip-forward-24` in case they dynamically use icons based on the screen resolution.

**Comment by CennoxX** [comment]
Okay, it works now.
> Maybe it is not a good idea to completely remove the play.spotify domain and old interface if the new layout is not (yet) rolled for everyone.
I added it back
> No idea why it would work for "next" but not for "play/pause". 
Found out, this was a browser side issue. So it works now.
> you might want to use spoticon-skip-forward-* instead of spoticon-skip-forward-24
done that

**Comment by carlin-q-scott** [comment]
Thanks for the PR @CennoxX . I'll push it out soon and sorry for the looooong delay everyone.
