### ISSUE TITLE
Linux issues

### ISSUE THREAD

**Issue by gmelikov** [carlin-q-scott/browser-media-keys#132]
There are many Linux issues (which may be closed because of xcb support), which are open.

@carlin-q-scott I'm ready to answer all Linux-specific issues, but it would be great if you grant me rights to close them. Thank you!

**Comment by maxcr** [comment]
I'm using Arch Linux and it doesn't work. Do I need to unbind them from being handled by gnome, before they can be used by the browser?

**Comment by carlin-q-scott** [comment]
@gmelikov sorry I missed this comment and offer of support from you last year. It's somewhat irrelevant now that Mozilla is handling the OS-specific issues but I granted you the access anyways. Thanks for your support.

**Comment by CheesecakeCG** [comment]
> EDIT: I disabled the media keys from being handled by gnome and they are now being correctly handled by the browser. Dank!
How do I disable Xfce from handling media keys? I don't have them bound to anything, but I suspect VLC to be the culprit.

**Comment by gmelikov** [comment]
@carlin-q-scott thank you, you can ping me freely on any Linux-related question.

@CheesecakeCG Xfce don't handling media keys https://help.ubuntu.com/community/XfceMultimediaKeys , you have to set them, see the link.
