### ISSUE TITLE
Select which sites are affected

### ISSUE THREAD

**Issue by theromi** [carlin-q-scott/browser-media-keys#146]
Currently, when multiple supported sites are open (Youtube, Google Play, etc.), the behaviour of this plugin is quite random. It'll play/pause some of the stuff, mostly the most recently opened.

Options to select the supported services would be awesome. I usually have multiple Youtube-Videos open at the same time and would still like to only control Google Play.

**Comment by carlin-q-scott** [comment]
This is already implemented by right-clicking on tabs you want to control and choosing "pin media keys". The pin will persist through restarts and if you pin multiple tabs then the most recently active one will be the one under control.

I really should create a landing page explaining all the features of this add-on but my webpage content skills aren't great.
