### ISSUE TITLE
Plugin will be permanently disabled with the release of FireFox 57

### ISSUE THREAD

**Issue by gdhughes5** [carlin-q-scott/browser-media-keys#148]
To keep compatibility with the latest version of Firefox, this addon must be ported over to WebExtensions.

**Comment by carlin-q-scott** [comment]
It's unfortunate that WebExtensions doesn't support ctypes. I'm mostly 
done with the port and it looks like I'll have to include a compiled 
binary for each platform to continue supporting the media keys. Thanks 
for reminding me of in the imminent doom.

**Comment by DavidCao22** [comment]
@carlin-q-scott Do you have an estimated release date for the WebExtension update?

**Comment by gdhughes5** [comment]
@carlin-q-scott Just glad to see that this project is still alive. Thanks for the response. Can't wait to get back to using the plugin.

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/108

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/149

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/150

**Comment by svnpenn** [comment]
@gdhughes5 why was this closed if WebExtension is still not implemented?

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/20

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/21

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/153

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/155
