### ISSUE TITLE
FF 57/WebExtension compatibility 

### ISSUE THREAD

**Issue by knobhead** [carlin-q-scott/browser-media-keys#149]
Hi, love this extension... Any chance to see it in Firefox 57 as a WebExtension?

**Comment by yfdyh000** [comment]
#148.

**Comment by knobhead** [comment]
Sorry, missed that one! Thanks! Glad we'll get back Media Keys for Christmas :-)

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/108

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/150

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/20

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/21

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/153

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/155
