### ISSUE TITLE
Extension is too convenient

### ISSUE THREAD

**Issue by merwok** [carlin-q-scott/browser-media-keys#152]
Hello!  After seeing a few chrome plugins, I searched on addons.mozilla.org and found your extension.  It installed without reboot and worked immediately.

* OS: Debian testing
* Version: Firefox ESR 52.3.0
* Keybooard: basic mechanical keyboard with a Play/Pause key

I expected more trouble.  Thanks a lot!

**Comment by carlin-q-scott** [comment]
Haha, I'm glad you like it.
