### ISSUE TITLE
Doesn't work with Firefox 57+ (new extension technology)

### ISSUE THREAD

**Issue by condab** [carlin-q-scott/browser-media-keys#153]
Apologies if I'm posting an obvious problem here, or if the developers are already working on the new version. Just thought I would bring this up as I just noticed that the extension was not working just today. This is explained here: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct

**Comment by AlmightyFloppyFish** [comment]
I think many, if not most Firefox users have already switched to the 57 beta since It's absolutely amazing. So making this compatible should be priority

**Comment by jerome-tgl** [comment]
Duplicate of #150

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/20

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/21

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/155

**Comment by MaxValue** [comment]
Please close this issue @condab, as it is a duplicate of #150.

**Comment by cup** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/158

**Comment by cup** [comment]
Note that Version 2.0.0 of this addon does not work with Firefox 56. Make sure
to turn Automatic Updates off.
