### ISSUE TITLE
Firefox Quantum compatibility

### ISSUE THREAD

**Issue by Sir4ur0n** [carlin-q-scott/browser-media-keys#155]
Hi,

Thanks for this plugin, quite useful :)
Unfortunately it is incompatible with the new Firefox Quantum (57.0+). Is there any plan to support this new version please?

**Comment by olessavluk** [comment]
Duplicate of #150

**Comment by Sir4ur0n** [comment]
My bad, I searched for "Quantum" in the issues and I couldn't find any.

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/20

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/21

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/108

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/148

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/149

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/153
