### ISSUE TITLE
This add-on is not compatible with your version of Firefox.

### ISSUE THREAD

**Issue by mfilippov** [carlin-q-scott/browser-media-keys#158]
I try to install extensions but it isn't possible.

**Comment by CennoxX** [comment]
see https://github.com/carlin-q-scott/browser-media-keys/issues/153

**Comment by cup** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/150

**Comment by cup** [comment]
Note that Version 2.0.0 of this addon does not work with Firefox 56. Make sure
to turn Automatic Updates off.
