### ISSUE TITLE
Support YouTube Music

### ISSUE THREAD

**Issue by Lolle2000la** [carlin-q-scott/browser-media-keys#164]
I use the extension often and am really happy with it. I would like to have support for [YouTube Music](https://music.youtube.com) as I use it a lot.
I think you did a great job with this extension!

**Comment by carlin-q-scott** [comment]
@Lolle2000la Are you indeed using the older extension that's not supported in the latest release of Firefox?

**Comment by Lolle2000la** [comment]
I'm on the most up to date version of firefox with the new extension. While YouTube works, YouTube Music (music.youtube.com) does not.

**Comment by Lolle2000la** [comment]
I tried, but for me all buttons only pause/play the current song, nothing else

**Comment by carlin-q-scott** [comment]
Oh, yeah, that's an issue with Firefox. All the media keys trigger the same action in all extensions. I found the cause of the issue in their code but it's really hard to fix.

**Comment by Lolle2000la** [comment]
Oh, ok. Then thank you for the time! I hope they are going to fix that at some point.
