### ISSUE TITLE
Dependency on GnomeSettingsDaemon, MPRIS support?

### ISSUE THREAD

**Issue by crespyl** [carlin-q-scott/browser-media-keys#20]
The README states that this addon requires DBUS/glib, but neglects to mention that it is using this to interact with the GnomeSettingsDaemon, which is usually only available when using Gnome.

I was at first really excited when I found this addon, then kind of disappointed when I couldn't make it work in my KDE desktop, then I got excited again when I realized that it was using DBUS.

Is there any chance I could convince you to switch from using GSD to instead exposing an [MPRIS](http://specifications.freedesktop.org/mpris-spec/latest/) service?
##

**Comment by carlin-q-scott** [comment]
It looks doable but @davidjb implemented the linux hotkeys. I need to re-install linux on my computer in order to work on this and that's probably not going to happen soon.

**Comment by davidjb** [comment]
@crespyl MPRIS looks like it's an interface for controlling/exposing a media player rather than listening to key presses directly as GSD does. The code is currently such that the media keys are 'grabbed' via GSD over DBus by Firefox and callbacks occur whenever keys are pressed and signals generated.

Looking at my system's DBus for an application like Rhythmbox, MPRIS signals are sent out after an action happens (eg Rhythmbox MPRIS PlaybackStatus is "Playing" or "Paused"), but no MPRIS signals are going to the application -- they're all via GSD MediaKeys.  I'd used this as the basis for my implementation, and I hadn't seen how/where any were listening to MPRIS.

How does your system translate media key presses into DBus signals?  It sounds like there needs to be two (or more) different implementations for Linux machines; unless something on GNOME's side is able to convert key presses -> MPRIS -> GSD MediaKeys.

If there needs to be more implementations, @carlin-q-scott's implementation is very modular!

**Comment by crespyl** [comment]
In my case, I used KDE's hotkey system to bind the media keys to scripts that run qdbus, pretty much what you can see [here](https://github.com/bastibe/KDE-Media-Keys).

I also use a plasmoid/widget that uses MPRIS to show track information and provide visual controls, though I don't think Plasma currently offers much in the way of hotkey support right now (individual plasmoids can have *a* hotkey to activate them, but I'm not sure if you can have more than one).

I *think* GSD is smart enough to automatically recognize MPRIS players and send them the right hotkey events, without the player having to do anything Gnome specific, aside from offering the MPRIS interface, but I don't use Gnome often so I'd have to double check.

**Comment by davidjb** [comment]
As far as I understand it, MPRIS players need to be controlled directly by name, whereas GSD is providing an abstraction layer.  In the case of GNOME applications, the key grab has to happen so GSD's MediaKeys will start listening to key presses & know where it needs to be sending the signals.  So the two are related in that they use DBus, but distinct in how they operate.

I've tried VLC (MPRIS compatible), and it accepts MPRIS commands over DBus but there's no translation between the GNOME's system key presses and MPRIS.  There's a [GNOME extension](https://extensions.gnome.org/extension/695/mediakeys-to-mpris2/) that acts as a shim, but nothing by default.

So to implement this, there'd need to be an MPRIS service exposed by this plugin, separate to the existing GSD-specific code.  The MPRIS service would need to be enabled for Linux platforms that don't support GSD and/or perhaps configured by an user setting; eg  for those GNOME users who want MPRIS support as well or instead. 

@crespyl, would you be looking at creating a PR?

**Comment by crespyl** [comment]
> @crespyl, would you be looking at creating a PR?

I spent some time poking around, but I'm not terribly familiar with GLib/ctypes, and I couldn't figure out how to adapt any of the existing JS DBus APIs (mostly node stuff) to work with FireFox/jpm, so I can't really promise anything.

I should have some more time over the weekend, but it's fine if you think this is out of scope for the addon.

**Comment by davidjb** [comment]
Scoping up to @carlin-q-scott but it'd definitely be useful for all non-GNOME Linux users.

Maybe my existing DBus code might help your cause; I'm unsure if the same libraries are recommended for use on KDE, but it could be a starting point.  The only major issue I had - aside from getting all the fiddly functions, data structures and types defined - was ensuring the ctypes libraries stayed open for JS callbacks.  The way it's coded now ensures the libraries stay open and Firefox doesn't crash when handling a callback.

**Comment by terax6669** [comment]
I have no idea what are you guys talking about, but I'll just ask if it's related and ask about any ETA?

Xubuntu 16.04 with Xfce 4.12
Firefox 46.0
Keyboard: Logitech Y-BL49A

libglib2.0-0 was already installed
Tried with both flash and html5 players on YouTube.
Yes, I've tried to disable all addons.

**Comment by gmelikov** [comment]
Please, look at #83 pull request, there are [instructions](https://github.com/gmelikov/browser-media-keys/blob/7feffdc17a50b428dfe04e828b6ae2869a9baebc/README.md) to simulate DBus services on other DE, it works on Xfce. I didn't use KDE, but as i see here https://techbase.kde.org/Development/Tutorials/D-Bus/Introduction , KDE has DBus too.

@terax6669, this method will work for you, i have Debian Jessie with Xfce and it works.
