### ISSUE TITLE
media keys are held on non video youtube pages

### ISSUE THREAD

**Issue by greatwroth** [carlin-q-scott/browser-media-keys#24]
The media keys are being held while the youtube subscription page or other non video page is open.

**Comment by carlin-q-scott** [comment]
How big of an irritation is this? It's definitely not easy to fix as it would probably take 4-8 hours to deal with.

**Comment by greatwroth** [comment]
I do normally have the youtube subscription page open nearly the entire time firefox is open but honestly not that big.

**Comment by carlin-q-scott** [comment]
Oh good! Thanks for reporting the issue though!
