### ISSUE TITLE
No link to github

### ISSUE THREAD

**Issue by Noitidart** [carlin-q-scott/browser-media-keys#28]
Hi there,
There is no link to the github repository (and/or issues page) from the AMO listing. This may not be an issue, but i just spent a while digging on github to find this repo :P

**Comment by carlin-q-scott** [comment]
There's actually a link in the [developers comment section of the listing](https://addons.mozilla.org/en-US/firefox/addon/media-keys/?src=api#developer-comments) but I understand that it isn't terribly prominent. What i find strange is that I gave Mozilla links to my github source and issues pages when creating the add-on and those aren't displayed anywhere.

Do you think I should move the link to the add-on description?

**Comment by Noitidart** [comment]
Interesting I'll take a look at your listing to see whats up.

**Comment by Noitidart** [comment]
Oh you put into the technical details portion: ![](http://i.imgur.com/1Xj6Kbz.png)
