### ISSUE TITLE
Linux: Doesn't work with playerctl for media control

### ISSUE THREAD

**Issue by alexmcnurlin** [carlin-q-scott/browser-media-keys#35]
OS: Ubuntu 15.04 Desktop
Desktop Environment: i3 ([gaps fork](https://github.com/Airblader/i3)), 4.11
Firefox: 43.0, 64-bit

I use [playerctl](https://github.com/acrisci/playerctl) to control my music on my computer. After downloading and installing this extension, it doesn't appear to work at all. I restarted Firefox, and even if the window is focused, it doesn't work. 

Sites tested: Youtube, Google Play Music, Spotify. 
##

**Comment by davidjb** [comment]
An MPRIS interface isn't currently implemented.  See #20.

**Comment by gmelikov** [comment]
Please, look at #83 pull request, there are [instructions](https://github.com/gmelikov/browser-media-keys/blob/7feffdc17a50b428dfe04e828b6ae2869a9baebc/README.md) to simulate DBus services on other DE, it works on Xfce.

**Comment by carlin-q-scott** [comment]
The mentioned PR was merged in but hasn't been release yet. Please confirm if the instructions provided in it solve your issue @alexmcnurlin .
