### ISSUE TITLE
Add support for Plex

### ISSUE THREAD

**Issue by joshdreagan** [carlin-q-scott/browser-media-keys#39]
Would be nice to add Plex support. Trick is that you can view your Plex library from "plex.tv" domain, or from localhost.

**Comment by joshdreagan** [comment]
Got something working. I'll create a pull request.

**Comment by carlin-q-scott** [comment]
Thanks for working on this Josh!

**Comment by joshdreagan** [comment]
No problem! Happy to contribute. Feel free to tweak it however you see fit.

**Comment by carlin-q-scott** [comment]
I'm curious about the localhost domain. Is it that because you're hosting your plex on your own computer? Couldn't it be on another computer on your network or even externally hosted? Jamstash is similar so I was thinking about copying the customizable domain settings for it.

**Comment by joshdreagan** [comment]
Yes. It's because it's hosted on my local computer. Technically, you can access your servers through "*.plex.tv" from anywhere, "<name>.local" if you're on the same network and have mdns, or "localhost" if you're on the same machine. Definitely feel free to improve and make it customizable. My feelings won't be hurt. :)

**Comment by carlin-q-scott** [comment]
heh, I'm glad you feel that way. I'll try to wrap this up today and make a release.

**Comment by davidjb** [comment]
FYI some comments on Plex support over at https://github.com/carlin-q-scott/browser-media-keys/pull/40#issuecomment-174415369 (mainly for benefit of @joshdreagan or anyone following along).

**Comment by carlin-q-scott** [comment]
I have implemented preferences for plex with 81ca1d1d01780fd7ed5bfc6a92690a1da8312ac3

**Comment by carlin-q-scott** [comment]
Oh, and plex support went live yesterday.

**Comment by davidjb** [comment]
:+1: looks awesome, thanks @carlin-q-scott.

**Comment by joshdreagan** [comment]
Good stuff!
