### ISSUE TITLE
Media Keys Stop Responding after extended use

### ISSUE THREAD

**Issue by CookieMonger** [carlin-q-scott/browser-media-keys#4]
After using this addon for an extended period of time, my media keys stop working.  Reloading the page does not resolve the issue and I am forced to restart Firefox to continue using my media keys.

**Comment by carlin-q-scott** [comment]
Thanks for reporting this issue. I think I am seeing something similar but I can resolve it by reloading the tab most of the time.

**Comment by CookieMonger** [comment]
No problem, I added support for spotify on my system and it occurred 
during normal use with that.  The issue persists across to pandora after 
it appears though so it shouldn't be the code I added causing the problem.

**Comment by carlin-q-scott** [comment]
Oh interesting. That would help me debug this issue then if you're willing to contribute your code.

**Comment by carlin-q-scott** [comment]
Version 0.4 addresses this issue. Should be out tomorrow.
