### ISSUE TITLE
Pandora Site Update Causing Issues

### ISSUE THREAD

**Issue by MoltenTesseract** [carlin-q-scott/browser-media-keys#43]
Pandora have updated their site a few days ago.

If pandora is playing in another tab and I hit pause on my keyboard, the song very slowly lowers its volume until it stops after about 10 seconds.

If during this "slow pause" process I switch to the tab, then it pauses instantly.

Trying to start audio is a bit hit and miss, sometimes it starts, sometimes it doesn't.

**Comment by carlin-q-scott** [comment]
Thanks for reporting this issue. After playing with it for a little while it seems that Pandora must be visible for the music to pause/resume. A dirty solution would be to make it visible when pressing play/pause but I don't like that solution very much.

**Comment by carlin-q-scott** [comment]
This issue doesn't seem to stick around. I tried reproducing on two other computers and couldn't. Today I tried reproducing this on the computer I used last time to reproduce it and now it's not happening.

Has this issue mysteriously gone away for you too?

**Comment by MoltenTesseract** [comment]
Yep. It's now working fine! Thanks for the quick response though!
