### ISSUE TITLE
Many relevant labels are missing in AMO entry

### ISSUE THREAD

**Issue by basilevs** [carlin-q-scott/browser-media-keys#45]
Consider adding following labels:
 - [media keys](https://addons.mozilla.org/ru/firefox/tag/media%20keys)
 - [global hotkeys](https://addons.mozilla.org/ru/firefox/tag/global%20hotkeys)

**Comment by carlin-q-scott** [comment]
Thanks for the suggestion. I have added those tags and a few variations of them.
