### ISSUE TITLE
Can't seem to get this to work in Linux

### ISSUE THREAD

**Issue by robcross** [carlin-q-scott/browser-media-keys#46]
Running Debian testing, Iceweasel 44.0.2. Pretty minimal install, startx with no display manager running awesomewm.

I've installed the latest version from the Firefox addon site and tried using both my keyboard and bluetooth headset next/previous buttons on youtube and jamstash. No combinations seem to do anything.

xev shows events for XF86Audio{Prev,Next,Play,Pause}.

I don't believe there are any other applications grabbing media keys (I had awesomewm binds, but I've removed them).

Any way I can debug this further?

**Comment by robcross** [comment]
nm I think this is a duplicate of #35 since I don't have gnome settings daemon.

**Comment by carlin-q-scott** [comment]
Yeah, I think this is a duplicate of that one. Linux is fortunate to have a very dynamic ecosystem of components for the OS but that makes it quite daunting to support all of them.
