### ISSUE TITLE
Feature Request: Bandcamp Support

### ISSUE THREAD

**Issue by SaberMage** [carlin-q-scott/browser-media-keys#5]
Please add support to control the Bandcamp media player. I'd also request YouTube, but I've noticed it is already in your plans. Thanks for your work!

**Comment by carlin-q-scott** [comment]
This will be in the next release (Version 0.4).

> The main page of Bandcamp has a bunch of play buttons so I only added the "main" one which covers everything except the "Bandcamp Weekly". All the band pages should be covered as well but please let me know if you have any issues.

I'm glad you are enjoying the add-on and thanks for providing feedback.
