### ISSUE TITLE
Can't get it to work and add supoort for Napster

### ISSUE THREAD

**Issue by kannwism** [carlin-q-scott/browser-media-keys#50]
I'm using Windows 10 and a Microsoft SideWinder X4 keyboard, but the add-on seems to do nothing.
Firefox is up to date.

Also support for Napster would be great.

Would be great to be able to use those media keys in Firefox.
##

**Comment by carlin-q-scott** [comment]
Microsoft's SideWinder app causes issues with this add-on. I don't know what the app is called but I believe you should be able to find and close it from your taskbar (lower-right). The latest code should handle the problem you're experiencing without needing to close the app but it's not ready for release yet.
