### ISSUE TITLE
Ability to enable/disable resume on stop (and pause on play)

### ISSUE THREAD

**Issue by mFoxRU** [carlin-q-scott/browser-media-keys#55]
The caption speaks for itself

**Comment by carlin-q-scott** [comment]
I'll add this soon but is there a particular issue you have with this feature that could be addressed? For instance I'd like to have it only resume playing something that was paused automatically.

**Comment by mFoxRU** [comment]
The main issue is that I'm not always sure what will happen when current media source will end playing.
Sometimes there are 2 embedded youtube videos on one page, and given I played only the second, after it ends the first one suddenly starts playing. Which is often undesirable. 
Sometimes I manually pause playback on one site, some time later I watch youtube video, and when I close youtube tab playback on the first site resumes. Which is even more undesirable. 
Resume on stop works when tabs are opened in different windows, but pause on play does not. Which makes it all even more unpredictable. 
For people who have like 10 tabs opened at the same time this could work, but I regularly have 2-3 windows with 50+ tabs. And when one of the tabs with embedded video suddenly starts playing it... Well, I'd rather control playback manually.

**Comment by carlin-q-scott** [comment]
Thanks for the feedback. I see three specific issues to address:
1. Allow disabling the feature right now until the following issues are resolved (the current issue)
2. Only resume automatically paused media
3. Enable cross-window automatic pause/resume

**Comment by carlin-q-scott** [comment]
This enhancement request is resolved by 1b088a4882d492e30ca7cdd5378ccd5ef2103e39
