### ISSUE TITLE
Lock media control to manually selected tab

### ISSUE THREAD

**Issue by mFoxRU** [carlin-q-scott/browser-media-keys#58]
Would be a nice feature. Dunno if and how this could be made though.

Use case: Ability to have a separate tab with music which could be controlled independently of other undesirable tabs that may also have media sources.

**Comment by carlin-q-scott** [comment]
This is dead simple in the add-on code but I have no idea how to provide a control to the user for pinning the media controls to a tab.

**Comment by carlin-q-scott** [comment]
What if I just cue off of pinned tabs? If you pin a media site tab then it will always be assigned the media keys. I'd have to make this an option you'd turn on in settings because I personally wouldn't use this feature.

**Comment by mFoxRU** [comment]
I've seen that some addons add buttons to tab context menu (i.e. [Duplicate in Tab Context Menu](https://addons.mozilla.org/en-US/firefox/addon/duplicate-in-tab-context-menu), [New Tab in Tab Context Menu](https://addons.mozilla.org/en-US/firefox/addon/new-tab-in-tab-context-menu).

**Comment by carlin-q-scott** [comment]
Yeah, I was thinking about doing that too but couldn't find the API documentation for it and it's difficult to locate the source for the Duplicate add-on. 

There's [documentation for context menus](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Add_a_Context_Menu_Item) but it only covers in-page context menus.

**Comment by mFoxRU** [comment]
Button is added in `duplicateintabcontext.xul`

**Comment by carlin-q-scott** [comment]
I couldn't use the method in that add-on because I'm using the Add-On SDK but I was able to find info on StackOverflow for doing it after learning some keywords from duplicateintabcontext.xul. I have pushed a new release (v0.7.2) to Mozilla which will have this feature.
