### ISSUE TITLE
Break reload command on tab.

### ISSUE THREAD

**Issue by ve3** [carlin-q-scott/browser-media-keys#67]
The last version of this plugin break the **reload tab** command.

To reproduce bug.
1. Open few tabs in **Firefox** with different websites.
2. Active on any tab you want.
3. Right click on tab
4. Click on **Reload Tab**

From last step, It should reload that tab but currently it is not.

Disable this plugin > Restart Firefox and **Reload Tab** command from right click works fine.

**Comment by carlin-q-scott** [comment]
I found this myself today as well. The whole menu, except for "pin media keys", doesn't work. Already fixed in next version that should available soon.
