### ISSUE TITLE
Playing youtube causes gpm on another window to start playing

### ISSUE THREAD

**Issue by meter1060** [carlin-q-scott/browser-media-keys#71]
Steps to reproduce:

1) Open up google play music and start streaming a playlist or a radio station
2) Pause the song.
3) Open a new tab and navigate to YouTube.
4) Move the GPM tab to a new window.
5) Start playing a new video.
6) Pause the video and play it right away (any time interval works).

Expected results:

1) YouTube plays without a hitch.

Actual results:

1) YouTube starts playing music, but so does Google Play Music in the other window.

Additional notes:

I don't think I can reproduce this while the two sites are in the same window, but only in separate windows.

**Comment by carlin-q-scott** [comment]
What happens if you turn off the autoplay feature in the add-on options?

**Comment by meter1060** [comment]
That removes the problem mentioned.

**Comment by carlin-q-scott** [comment]
I should probably disable autoplay by default until these kinds of kinks are worked out.

Issue #60 handles this issue I believe so I'm closing it.
