### ISSUE TITLE
Spotify is permanently pinned

### ISSUE THREAD

**Issue by Zaggy1024** [carlin-q-scott/browser-media-keys#72]
A while back I pinned Spotify to avoid the issue where non-video pages on YouTube capture the media key focus, but now the Spotify tab shows "Pin Media Keys" instead of "Unpin" and trying to pin another tab has no effect.

Also, I'm not sure how the pinning is supposed to work, does it limit the keys to affecting a set of tabs, or is supposed to only allow one tab pinned at a time?

**Comment by carlin-q-scott** [comment]
It's supposed to work like it does without pins at all except it limits itself to only working with pinned tabs. So you can pin spotify and youtube, then open google play but continue controlling spotify or youtube, depending on which one was most recently active.

There's some weirdness around the text shown in the context menu but the rest of the pinning functionality should be working.

**Comment by Zaggy1024** [comment]
It doesn't seem to work the way I would expect it to, though. If I select the "Pin" option while Spotify is pinned it doesn't switch to allowing a YouTube video to be controlled instead. Also, if I attempt to pin a YouTube page it still only controls Spotify.

**Comment by carlin-q-scott** [comment]
I'm going to track this in #73
