### ISSUE TITLE
Mark as multiprocess compat

### ISSUE THREAD

**Issue by Noitidart** [carlin-q-scott/browser-media-keys#91]
Need to mark compatible with multiprocess - https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/

in package.json permission: { multiprocess: true }

https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json#Key_reference

**Comment by carlin-q-scott** [comment]
Fixed with 9562a833dd
